"""Shared helpers for the data pipeline scripts.

All scripts are meant to be run from the repository root, e.g.::

    python scripts/download_open_data.py
    python scripts/build_metro_network.py

Only the Python standard library is required.
"""

from __future__ import annotations

import json
import os
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "data" / "raw"
JS_DATA_DIR = REPO_ROOT / "js" / "data"

USER_AGENT = "milano-transit-simulator/1.0 (+https://github.com/DeveloperMatt02/milano-transit-simulator)"

# A "service day" starts at 03:00 and ends at 03:00 of the next calendar day.
# Times after midnight belong to the previous service day and are stored as
# values >= 24:00 (e.g. 00:30 -> 24:30). The JavaScript engine uses the same
# convention (see js/utils.js).
SERVICE_DAY_START_MIN = 3 * 60


def hhmm_to_minutes(value: str) -> int | None:
    """Parse a "HH:MM" string into minutes after midnight (None if invalid)."""
    try:
        hours, minutes = value.strip().split(":")[:2]
        h, m = int(hours), int(minutes)
    except (AttributeError, ValueError):
        return None
    if not (0 <= h < 48 and 0 <= m < 60):
        return None
    return h * 60 + m


def to_service_minutes(minutes: int) -> int:
    """Map a clock time (minutes after midnight) onto the service-day timeline."""
    return minutes + 24 * 60 if minutes < SERVICE_DAY_START_MIN else minutes


def minutes_to_hhmm(minutes: int) -> str:
    """Format minutes as "HH:MM" (values >= 24:00 are kept, e.g. "24:30")."""
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def download(url: str, destination: Path, *, overwrite: bool = False) -> Path:
    """Download ``url`` into ``destination`` unless it already exists."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() and not overwrite:
        print(f"  = {destination.relative_to(REPO_ROOT)} already present, skipping")
        return destination
    print(f"  ↓ {url}")
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=120) as response:
        destination.write_bytes(response.read())
    print(f"  ✓ saved {destination.relative_to(REPO_ROOT)} ({destination.stat().st_size:,} bytes)")
    return destination


def write_js_constant(path: Path, const_name: str, data, header: str, *, compact: bool = False) -> None:
    """Write ``data`` as ``const NAME = {...};`` so it can be loaded with a classic <script> tag.

    The file also exports the constant for Node.js so that the test-suite can ``require`` it.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if compact:
        payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    else:
        payload = json.dumps(data, ensure_ascii=False, indent=2)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(f"// {header}\n")
        handle.write("// AUTO-GENERATED by the scripts in /scripts - do not edit by hand.\n")
        handle.write(f"const {const_name} = {payload};\n\n")
        handle.write("if (typeof module !== \"undefined\" && module.exports) {\n")
        handle.write(f"  module.exports = {const_name};\n")
        handle.write("}\n")
    print(f"  ✓ wrote {path.relative_to(REPO_ROOT)} ({os.path.getsize(path):,} bytes)")
